services:
  db:
    extends:
      file: docker-compose.base.yml
      service: db

  web:
    extends:
      file: docker-compose.base.yml
      service: web

  migration:
    extends:
      file: docker-compose.base.yml
      service: migration

  react-client:
    extends:
      file: docker-compose.base.yml
      service: react-client

volumes:
  postgres_data:

networks:
  db: